experiment_name: "NeOTF" # Name of the experiment
output_dir: "./outputs" # Directory to save outputs

data:
  path: "./experimental_speckles" # Path to the folder containing preprocessed images
  format: "tif" # Image format: "png", "jpg", "jpeg", "tif", etc.
  supp_size_w: 25 # Support size width
  supp_size_h: 25 # Support size height

model:
  type: "SIREN" # Model type: "SIREN" or "MLP"
  in_features: 2 # Input features (e.g., 2 for 2D coordinates)
  hidden_layers: 3 # Number of hidden layers
  hidden_features: 128 # Number of features in hidden layers
  out_features: 1 # Output features (e.g., 1 for grayscale output)
  first_omega_0: 30 # Omega_0 for the first layer
  hidden_omega_0: 30 # Omega_0 for hidden layers
  outermost_linear: True # Whether the outermost layer is linear (True/False)
  num_frequencies: 10 # Number of frequencies for Fourier feature encoding


training:
  random_seed: False # Whether to use a random seed
  seed: 7204  # Random seed value (if random_seed is false)
  device: "cuda"  # or "cpu"
  epochs: 5000 
  optimizer: "Adam"  # or "SGD"
  lr: !!float 1e-4
  loss: "L1"  # or "MSE"
  scheduler: "none" # Whether to use learning rate scheduling
  center_sample: False # Whether to use center sampling
  center_sample_radius: 0.5
  random_sample: False # Whether to use random sampling
  random_sample_ratio: 0.1

  tv_regularization: False # Whether to use TV regularization
  tv_weight: !!float 1e-4

  num_frames: 5 # Number of frames for optimize model
